name: application composition analysis

on:
  push:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        id: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: code analysis
        id: code
        uses: SecureStackCo/actions-code@v0.1.1
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: critical
          language: node