name: Build and push project

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: checkout code
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: build and push docker
      with:
        image: catovh/ci-cd
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}