name: container scan for vulnerabilities

on:
  push:
    branch: [ master ]
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: catovh/app:latest
      - name: scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: catovh/app:latest
          severity_threshold: HIGH
          annotations: true
      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: output/vuln.txt